// @ts-nocheck
import { Box, Card as MuiCard, Stack, Typography } from '@mui/material'
import type { PlayerCard } from './gameDashboardCardTypes'
import { costStructureIcons, dashboardCardColors } from './gameDashboardCardTheme'

const managementIcons: Record<string, string> = { operations: '⚙', coffee: '☕', value: '♥', channel: '⚑', marketing: '⚑', people: '♟' }

export function ManagementCardTile({ card, selected, onClick }: { card: PlayerCard; selected?: boolean; onClick?: () => void }) {
  const meta = dashboardCardColors.management[card.kind]
  if (!meta) return null
  const marketEntries = Object.entries(card.marketChange ?? {}).filter(([key, value]) => (key === 'gourmet' || key === 'regular') && value !== 0)
  return <MuiCard onClick={onClick} variant="outlined" sx={{ display: 'flex', height: '100%', minHeight: 290, flexDirection: 'column', overflow: 'hidden', cursor: onClick ? 'pointer' : 'default', bgcolor: meta.pale, borderColor: selected ? meta.color : `${meta.color}66`, borderWidth: selected ? 3 : 1 }}><Box sx={{ minHeight: 39, px: 1.5, py: .9, boxSizing: 'border-box', bgcolor: meta.color, color: 'white', textAlign: 'center' }}><Typography variant="caption" fontWeight={900}>{card.name}</Typography></Box><Box sx={{ display: 'flex', minHeight: 57, flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: .2, px: 1.5, py: .85, boxSizing: 'border-box', bgcolor: `${meta.color}dd`, color: 'white' }}><Typography variant="caption" sx={{ opacity: .8 }}>卡片功能</Typography><Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: .8 }}>{card.kind === 'resource' ? costStructureIcons.map(({ id, icon: Icon }) => <Icon key={id} sx={{ fontSize: 24 }} titleAccess={costStructureIcons.find((item) => item.id === id)?.label} />) : card.icons.slice(0, 4).map((icon, index) => <Typography key={`${icon}-${index}`} sx={{ fontSize: 24 }}>{managementIcons[icon] ?? '◆'}</Typography>)}</Box></Box><Box sx={{ display: 'grid', minHeight: 105, flex: '0 0 105px', placeItems: 'center', color: meta.color, background: 'linear-gradient(145deg, #f0f0ed, #dfe1df)' }}><Typography sx={{ fontSize: 46 }}>{managementIcons[card.icons[0]] ?? '◆'}</Typography></Box><Box sx={{ minHeight: 88, flex: 1, px: 1.5, py: 1, boxSizing: 'border-box', bgcolor: '#ffffffcc' }}><Typography variant="caption" color="text.secondary">卡片說明</Typography><Typography variant="body2" sx={{ minHeight: 34 }}>{card.description ?? '可執行的經營管理行動。'}</Typography></Box><Stack direction="row" justifyContent="space-between" sx={{ minHeight: 42, alignItems: 'center', px: 1.5, py: .8, boxSizing: 'border-box', bgcolor: meta.pale }}><Box sx={{ minWidth: 82 }}><Typography variant="caption">成本</Typography><Typography display="block" variant="body2" fontWeight={900} color={meta.color}>${card.cost?.cash ?? 0}</Typography></Box><Box sx={{ display: 'flex', width: 38, justifyContent: 'flex-end', gap: .25, textAlign: 'right' }}>{marketEntries.map(([key, value]) => <Typography key={key} component="span" aria-label={key === 'gourmet' ? '饕客市場變動' : '一般客市場變動'} fontWeight={900} sx={{ color: key === 'gourmet' ? '#ff7900' : '#e5b832', letterSpacing: '-.08em', whiteSpace: 'nowrap' }}>{'★'.repeat(Math.abs(value))}</Typography>)}</Box></Stack></MuiCard>
}
