// @ts-nocheck
import { Box, Card as MuiCard, Stack, Typography } from '@mui/material'
import type { PlayerCard } from './gameDashboardCardTypes'
import { dashboardCardColors } from './gameDashboardCardTheme'
import { CardArtwork } from './CardArtwork'
import { GameIcon } from './GameIcon'

export function ManagementCardTile({ card, selected, onClick }: { card: PlayerCard; selected?: boolean; onClick?: () => void }) {
  const meta = dashboardCardColors.management[card.function ?? card.kind]
  if (!meta) return null
  const marketEntries = Object.entries(card.marketChange ?? {}).filter(([key, value]) => (key === 'gourmet' || key === 'regular') && value !== 0)
  const customerEntries = Object.entries(card.customerCount ?? {}).filter(([key, value]) => (key === 'gourmet' || key === 'regular') && value !== 0)
  const visibleCustomerEntries = customerEntries.length > 0 ? customerEntries : marketEntries.length > 0 ? marketEntries : [['regular', 1]]
  const visibleMarketEntries = card.kind === 'channel' ? visibleCustomerEntries : marketEntries
  return <MuiCard onClick={onClick} variant="outlined" sx={{ display: 'flex', height: '100%', minHeight: 290, flexDirection: 'column', overflow: 'hidden', cursor: onClick ? 'pointer' : 'default', bgcolor: meta.pale, borderColor: selected ? meta.color : `${meta.color}66`, borderWidth: selected ? 3 : 1 }}><Box sx={{ minHeight: 39, px: 1.5, py: .9, boxSizing: 'border-box', bgcolor: meta.color, color: 'white', textAlign: 'center' }}><Typography variant="caption" fontWeight={900}>{card.name}</Typography></Box><Box sx={{ display: 'flex', height: 88, flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: .2, px: 1.5, py: .85, boxSizing: 'border-box', bgcolor: `${meta.color}dd`, color: 'white' }}><Typography variant="caption" sx={{ opacity: .8 }}>卡片功能</Typography><Box sx={{ display: 'flex', minWidth: 0, maxWidth: '100%', alignItems: 'center', justifyContent: 'center', gap: .8, overflow: 'hidden' }}>{card.kind === 'channel' ? visibleMarketEntries.map(([key, value]) => <Typography key={key} component="span" fontWeight={900} sx={{ color: key === 'gourmet' ? '#ff7900' : '#e5b832', fontSize: 24, letterSpacing: '-.08em', lineHeight: 1, whiteSpace: 'nowrap' }}>{'★'.repeat(Math.max(1, Math.abs(value)))}</Typography>) : card.kind === 'resource' ? ['data', 'marketing_resource', 'operations', 'procurement'].map((icon) => <GameIcon key={icon} name={icon} sx={{ fontSize: 24 }} />) : card.icons.slice(0, 4).map((icon, index) => <GameIcon key={`${icon}-${index}`} name={icon} sx={{ fontSize: 24 }} />)}</Box></Box><Box sx={{ display: 'grid', height: 105, flex: '0 0 105px', placeItems: 'center', overflow: 'hidden' }}><CardArtwork card={card} /></Box><Box sx={{ minHeight: 88, flex: 1, px: 1.5, py: 1, boxSizing: 'border-box', bgcolor: '#ffffffcc' }}><Typography variant="caption" color="text.secondary">卡片說明</Typography><Typography variant="body2" sx={{ minHeight: 34 }}>{card.description ?? '可執行的經營管理行動。'}</Typography></Box><Stack direction="row" justifyContent="space-between" sx={{ minHeight: 42, alignItems: 'center', px: 1.5, py: .8, boxSizing: 'border-box', bgcolor: meta.pale }}><Box sx={{ minWidth: 82 }}><Typography variant="caption">成本</Typography><Typography display="block" variant="body2" fontWeight={900} color={meta.color}>${card.cost?.cash ?? 0}</Typography></Box><Box sx={{ display: 'flex', width: 38, justifyContent: 'flex-end', gap: .25, textAlign: 'right' }}>{visibleMarketEntries.map(([key, value]) => <Typography key={key} component="span" aria-label={key === 'gourmet' ? '饕客市場變動' : '一般客市場變動'} fontWeight={900} sx={{ color: key === 'gourmet' ? '#ff7900' : '#e5b832', letterSpacing: '-.08em', whiteSpace: 'nowrap' }}>{'★'.repeat(Math.max(1, Math.abs(value)))}</Typography>)}</Box></Stack></MuiCard>
}
