import type { CashFlowStatement, GameState } from '../../model/gameTypes'

export function CashFlowTable(props: { room: GameState }) {
  const statements = new Map((props.room.me?.cashFlow ?? []).map((statement) => [statement.period, statement]))
  const latestRounds = new Map((props.room.me?.cashFlowRounds ?? []).map((statement) => [statement.period, statement]))
  const periods = [1, 2, 3]
  const money = (value: number | undefined, signed = false) => value === undefined ? '待結算' : `${value < 0 ? '-$' : signed && value > 0 ? '+$' : '$'}${Math.abs(value)}萬`
  const statementFor = (period: number) => statements.get(period) ?? (period === props.room.period ? latestRounds.get(period) : undefined)
  const cell = (period: number, field: keyof CashFlowStatement, signed = false) => money(statementFor(period)?.[field] as number | undefined, signed)
  const customerFormula = (period: number, countField: 'gourmetCustomerCount' | 'regularCustomerCount', revenueField: 'gourmetRevenue' | 'regularRevenue') => {
    const statement = statementFor(period)
    if (!statement) return '待結算'
    const count = statement[countField] ?? 0
    const revenue = statement[revenueField] ?? 0
    const unitPrice = count > 0 ? revenue / count : 0
    return `${unitPrice} × ${count} = $${revenue}萬`
  }
  return <section className="cash-flow-panel panel" aria-label="現金流量表"><div className="cash-flow-heading"><div><p className="eyebrow">CASH FLOW STATEMENT</p><h2>現金流量表</h2><p>每回合結束更新目前期；第 6 回合完成後，再補上營收與利息結算。</p></div><span>單位：萬元</span></div><div className="cash-flow-grid"><div className="cash-flow-corner">項目</div>{periods.map((period) => <div className={`cash-flow-period ${props.room.period === period ? 'is-current' : ''}`} key={period}><strong>{period}</strong><small>{period === 1 ? '試營運' : period === 2 ? '正式營運' : '擴大營運'}</small></div>)}<div className="cash-flow-section">A. 期初現金</div>{periods.map((period) => <div className="cash-flow-value" key={`beginning-${period}`}>{cell(period, 'beginningCash')}</div>)}<div className="cash-flow-section">B. 營業收入</div>{periods.map((period) => <div className="cash-flow-value positive" key={`revenue-${period}`}>{cell(period, 'operatingRevenue', true)}</div>)}<div className="cash-flow-detail">B1. 饕客營收</div>{periods.map((period) => <div className="cash-flow-value detail" key={`gourmet-${period}`}>{customerFormula(period, 'gourmetCustomerCount', 'gourmetRevenue')}</div>)}<div className="cash-flow-detail">B2. 一般客營收</div>{periods.map((period) => <div className="cash-flow-value detail" key={`regular-${period}`}>{customerFormula(period, 'regularCustomerCount', 'regularRevenue')}</div>)}<div className="cash-flow-detail">B3. 棄牌補貼</div>{periods.map((period) => <div className="cash-flow-value detail" key={`other-${period}`}>{cell(period, 'otherIncome', true)}</div>)}<div className="cash-flow-section">C. 營運支出</div>{periods.map((period) => <div className="cash-flow-value negative" key={`expense-${period}`}>{cell(period, 'operatingExpenses', true)}</div>)}<div className="cash-flow-section">D. 籌資活動</div>{periods.map((period) => { const statement = statementFor(period); const financing = statement ? statement.newLoans - statement.interestPaid - statement.principalRepayment : undefined; return <div className="cash-flow-value" key={`financing-${period}`}>{money(financing, true)}</div> })}<div className="cash-flow-detail">D1. 支付利息</div>{periods.map((period) => <div className="cash-flow-value detail negative" key={`interest-${period}`}>{cell(period, 'interestPaid', true)}</div>)}<div className="cash-flow-detail">D2. 償還本金</div>{periods.map((period) => <div className="cash-flow-value detail negative" key={`principal-${period}`}>{cell(period, 'principalRepayment', true)}</div>)}<div className="cash-flow-detail">D3. 增貸資金</div>{periods.map((period) => <div className="cash-flow-value detail positive" key={`loans-${period}`}>{cell(period, 'newLoans', true)}</div>)}<div className="cash-flow-total">期末結餘（A+B+C+D）</div>{periods.map((period) => <div className="cash-flow-value cash-flow-total" key={`ending-${period}`}>{cell(period, 'endingCash')}</div>)}</div></section>
}
